services:
  - type: web
    name: gurgaon-property-leads
    runtime: node
    plan: free
    buildCommand: npm install && node server/seed.js && node server/seed-properties.js && node server/seed-owners.js
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        value: 806692116297-tvo0mmiire2auq4nsrbubmo1uuh1gekh.apps.googleusercontent.com
