require("dotenv").config();
const db = require("./db");

const gurgaon = [
  { name: "Ritika Oberoi", phone: "9810998877", email: "ritika.oberoi@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "Golf Course Road", budgetMin: 60000000, budgetMax: 120000000, timeline: "Immediately", status: "negotiating", source: "Client Referral", projects: "DLF The Camellias, The Magnolias", notes: "Fashion designer. Wants duplex penthouse. Sky garden or private terrace mandatory. Interior budget separate." },
  { name: "Sandeep Batra", phone: "9650112233", email: "sandeep.batra@icloud.com", leadType: "buyer", propertyType: "3BHK", area: "Golf Course Road", budgetMin: 25000000, budgetMax: 45000000, timeline: "1-3 months", status: "interested", source: "99acres", projects: "Ireo Grand Arch, DLF Park Place", notes: "Senior partner at law firm. Wants quiet floor away from road noise. Club membership included preferred." },
  { name: "Taruna Mehra", phone: "9871334455", email: "taruna.m@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Dwarka Expressway", budgetMin: 5000000, budgetMax: 8000000, timeline: "6-12 months", status: "new", source: "Facebook Ads", projects: "Hero Homes, Signature Global", notes: "BPO team lead. Night shifts. Needs soundproof flat. Under-construction okay for lower EMI. Metro proximity." },
  { name: "Vishal Taneja", phone: "9999556677", email: "vishal.taneja@outlook.com", leadType: "buyer", propertyType: "3BHK", area: "Dwarka Expressway", budgetMin: 9000000, budgetMax: 16000000, timeline: "1-3 months", status: "contacted", source: "Housing.com", projects: "Sobha City, Godrej Meridien, ATS Tourmaline", notes: "Chartered accountant. Relocating from Delhi. Family of 5. Wants 3BHK with study room. Prefer east-facing." },
  { name: "Nisha Arora", phone: "9812667788", email: "nisha.arora@gmail.com", leadType: "buyer", propertyType: "Villa", area: "Sohna Road", budgetMin: 15000000, budgetMax: 30000000, timeline: "3-6 months", status: "site-visit", source: "WhatsApp", projects: "Central Park Resorts, Experion Windchants", notes: "Yoga instructor. Wants villa with private garden and meditation room. Eco-friendly construction preferred." },
  { name: "Kunal Saxena", phone: "9718889900", email: "kunal.s@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Sohna Road", budgetMin: 6000000, budgetMax: 11000000, timeline: "Immediately", status: "new", source: "Landing Page", projects: "M3M Woodshire, Signature Global City", notes: "Works at Maruti Suzuki Manesar. Wants affordable 3BHK. EV charging point in parking would be great." },
  { name: "Aditi Chawla", phone: "9873001122", email: "aditi.chawla@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "Golf Course Ext Road (GCER)", budgetMin: 25000000, budgetMax: 45000000, timeline: "1-3 months", status: "interested", source: "99acres", projects: "M3M Golf Hills, Emaar Digi Homes", notes: "CTO at fintech startup. Wants smart home features — automated blinds, central AC, home automation." },
  { name: "Rajat Khurana", phone: "9910223344", email: "rajat.khurana@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Golf Course Ext Road (GCER)", budgetMin: 14000000, budgetMax: 22000000, timeline: "3-6 months", status: "contacted", source: "Public Form", projects: "Emaar Palm Heights, M3M Merlin", notes: "Dual income — both in consulting. Want modern flat with co-working lounge in society. Near Rapid Metro." },
  { name: "Bhavna Gupta", phone: "9654445566", email: "bhavna.g@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Sector 76-81", budgetMin: 4000000, budgetMax: 7000000, timeline: "Immediately", status: "new", source: "Facebook Ads", notes: "Single mom. Works at Convergys. Budget is tight. Needs safe area with good school nearby. PMAY eligible." },
  { name: "Siddharth Malhotra", phone: "9811667788", email: "sid.malhotra@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Sector 82-89", budgetMin: 7000000, budgetMax: 12000000, timeline: "3-6 months", status: "interested", source: "WhatsApp", projects: "Conscient Habitat 78, Pareena", notes: "Software developer at Paytm. Works from home 3 days. Needs extra room as office. Fiber internet essential." },
  { name: "Megha Rastogi", phone: "9876778899", email: "megha.r@gmail.com", leadType: "buyer", propertyType: "Plot", area: "Sector 90-95", budgetMin: 8000000, budgetMax: 18000000, timeline: "6-12 months", status: "contacted", source: "Landing Page", notes: "Builder herself. Wants plot to develop 4 independent floors. Corner plot preferred. Min 250 sq yard." },
  { name: "Ashutosh Pandey", phone: "9650889900", email: "ashutosh.p@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "DLF Phase 3", budgetMin: 35000000, budgetMax: 60000000, timeline: "1-3 months", status: "site-visit", source: "Builder Referral", notes: "VP at Goldman Sachs. Wants DLF Phase 3 independent floor. 400 sq yard. Builder floor with lift." },
  { name: "Reema Kapoor", phone: "9999001122", email: "reema.kapoor@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "DLF Phase 4", budgetMin: 20000000, budgetMax: 35000000, timeline: "3-6 months", status: "interested", source: "Housing.com", notes: "Interior designer. Wants raw flat she can customize. DLF Phase 4 for proximity to Galleria Market." },
  { name: "Nitin Sachdeva", phone: "9810334455", email: "nitin.s@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Cyber City", budgetMin: 40000000, budgetMax: 80000000, timeline: "Immediately", status: "negotiating", source: "Client Referral", notes: "SaaS startup. 80 employees. Needs 5000-8000 sq ft office. Open floor plan. Near metro. 24x7 access." },
  { name: "Pallavi Sethi", phone: "9871556677", email: "pallavi.sethi@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Sushant Lok 2", budgetMin: 10000000, budgetMax: 18000000, timeline: "1-3 months", status: "new", source: "99acres", notes: "Dentist. Wants ground floor with option to convert one room into clinic. Corner unit preferred." },
  { name: "Gaurav Dhingra", phone: "9718001122", email: "gaurav.dhingra@gmail.com", leadType: "buyer", propertyType: "Villa", area: "Palam Vihar", budgetMin: 12000000, budgetMax: 25000000, timeline: "3-6 months", status: "interested", source: "WhatsApp", notes: "Wants builder floor in Palam Vihar. Top floor with terrace rights. 200 sq yard plot. South-facing." },
  { name: "Swati Ahuja", phone: "9812990011", email: "swati.ahuja@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Sector 58-67", budgetMin: 6000000, budgetMax: 10000000, timeline: "Immediately", status: "new", source: "Public Form", projects: "Emaar Emerald Hills, BPTP Terra", notes: "Newly married. First home. Husband works at Wipro Cyber City. Want under 30 min commute." },
  { name: "Tarun Miglani", phone: "9650223344", email: "tarun.m@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "SPR (Southern Peripheral Rd)", budgetMin: 8000000, budgetMax: 15000000, timeline: "3-6 months", status: "contacted", source: "99acres", projects: "Bestech Park View, SS Hibiscus", notes: "Works at American Express. Wants society with tennis court. Active lifestyle. Near SPR for easy commute." },
  { name: "Anu Malhotra", phone: "9999334455", email: "anu.malhotra@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "MG Road", budgetMin: 30000000, budgetMax: 60000000, timeline: "1-3 months", status: "site-visit", source: "Builder Referral", notes: "Restaurant chain owner. Wants 2000-3000 sq ft for premium dining. Ground floor. High ceiling mandatory." },
  { name: "Deepika Chadha", phone: "9810556677", email: "deepika.c@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Sector 47-49", budgetMin: 12000000, budgetMax: 22000000, timeline: "Immediately", status: "interested", source: "Housing.com", projects: "Vipul Belmonte, Unitech Horizons", notes: "HR head at Deloitte. Single. Wants walkable to Cyber Hub. Modern gym in society. Pet-friendly building." },
  { name: "Mohit Grover", phone: "9871778899", email: "mohit.grover@gmail.com", leadType: "buyer", propertyType: "Plot", area: "Sector 68-75", budgetMin: 15000000, budgetMax: 28000000, timeline: "6-12 months", status: "new", source: "Facebook Ads", notes: "Real estate investor. Wants corner plot 300+ sq yard. HUDA allotment preferred. Will develop builder floors." },
  { name: "Sakshi Bhasin", phone: "9654667788", email: "sakshi.b@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Sector 99-104 (Dwarka Exp)", budgetMin: 5000000, budgetMax: 9000000, timeline: "3-6 months", status: "contacted", source: "Landing Page", projects: "Godrej Summit, M3M Antalya Hills", notes: "Works at IGI Airport. Dwarka Expressway for short commute. Under-construction okay. Wants balcony." },
  { name: "Rohit Sehgal", phone: "9718334455", email: "rohit.sehgal@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "South City 1", budgetMin: 18000000, budgetMax: 30000000, timeline: "1-3 months", status: "interested", source: "Client Referral", notes: "Joint family. Parents + wife + 2 kids. Wants spacious flat. South City for established infrastructure." },
  { name: "Kaveri Nanda", phone: "9812001122", email: "kaveri.n@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Sector 54-57", budgetMin: 15000000, budgetMax: 28000000, timeline: "3-6 months", status: "site-visit", source: "99acres", projects: "Park View Spa, Unitech Nirvana Country", notes: "Architect. Wants well-designed flat with natural light. Close to Sector 55-56 market. Terrace access nice." },
  { name: "Arun Sagar", phone: "9999778899", email: "arun.sagar@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Udyog Vihar", budgetMin: 25000000, budgetMax: 50000000, timeline: "Immediately", status: "negotiating", source: "99acres", notes: "Logistics company. Needs warehouse 10000 sq ft. Loading dock essential. Near NH-48 for truck access." },
];

const ludhiana = [
  { name: "Jaspreet Singh Brar", phone: "9814998877", email: "jaspreet.brar@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "Ludhiana — Model Town", budgetMin: 12000000, budgetMax: 22000000, timeline: "1-3 months", status: "site-visit", source: "Client Referral", notes: "NRI from New Zealand. Building retirement home. Wants 350 sq yard kothi. Modular kitchen. RO+AC pre-installed." },
  { name: "Asha Rani", phone: "9876998877", email: "asha.rani@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Ludhiana — Model Town", budgetMin: 7000000, budgetMax: 12000000, timeline: "3-6 months", status: "interested", source: "Housing.com", notes: "Retired principal. Pension + rental income. Wants ground floor flat. Walking distance to market and park." },
  { name: "Kulbir Singh", phone: "9815887766", email: "kulbir.s@gmail.com", leadType: "buyer", propertyType: "Villa", area: "Ludhiana — Sarabha Nagar", budgetMin: 25000000, budgetMax: 50000000, timeline: "Immediately", status: "negotiating", source: "Builder Referral", notes: "Pharma distributor. Wants corner kothi 400+ sq yard. Triple-story with lift. Marble flooring throughout." },
  { name: "Meenakshi Jain", phone: "9872887766", email: "meenakshi.j@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Ludhiana — Sarabha Nagar", budgetMin: 10000000, budgetMax: 18000000, timeline: "3-6 months", status: "interested", source: "99acres", notes: "Wants luxury flat in Sarabha Nagar society. Husband is cardiologist at DMCH. Near DMCH preferred." },
  { name: "Navtej Singh", phone: "9814776655", email: "navtej.s@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Ludhiana — BRS Nagar", budgetMin: 5000000, budgetMax: 9000000, timeline: "1-3 months", status: "new", source: "WhatsApp", projects: "Maya Garden City, Savitry Towers", notes: "Runs coaching center for IELTS. Wants flat that can double as small office. Ground floor with separate entry." },
  { name: "Simmi Kapoor", phone: "9876776655", email: "simmi.k@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Ludhiana — BRS Nagar", budgetMin: 3500000, budgetMax: 6000000, timeline: "6-12 months", status: "contacted", source: "Public Form", notes: "Beautician. Runs salon from home. Wants flat where home business is allowed. Needs extra power connection." },
  { name: "Harpal Singh Dhillon", phone: "9815665544", email: "harpal.dhillon@gmail.com", leadType: "buyer", propertyType: "Plot", area: "Ludhiana — Dugri", budgetMin: 5000000, budgetMax: 10000000, timeline: "3-6 months", status: "interested", source: "99acres", notes: "Wants residential plot 150-200 sq yard. MC approved colony. Near Dugri Phase 2. Plans to build 2-story." },
  { name: "Rashmi Sood", phone: "9872665544", email: "rashmi.sood@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Ludhiana — Dugri", budgetMin: 4000000, budgetMax: 7000000, timeline: "Immediately", status: "new", source: "Facebook Ads", notes: "Widow. School teacher. Two daughters. Needs safe and affordable. Near BCM or Sacred Heart School." },
  { name: "Rajwinder Kaur", phone: "9814554433", email: "rajwinder.k@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Ludhiana — Pakhowal Road", budgetMin: 15000000, budgetMax: 30000000, timeline: "1-3 months", status: "site-visit", source: "Housing.com", notes: "Wants SCO for boutique + tailoring unit. 1500-2500 sq ft. Pakhowal Road for NRI customer footfall." },
  { name: "Sahil Khanna", phone: "9876554433", email: "sahil.khanna@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Ludhiana — Pakhowal Road", budgetMin: 8000000, budgetMax: 15000000, timeline: "3-6 months", status: "interested", source: "Landing Page", notes: "Wants clinic space for dental practice. 800-1200 sq ft. Ground or first floor. Lift mandatory." },
  { name: "Mohinder Singh", phone: "9815443322", email: "mohinder.s@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Ludhiana — Ferozepur Road", budgetMin: 4500000, budgetMax: 8000000, timeline: "3-6 months", status: "contacted", source: "WhatsApp", projects: "Maya Garden Magnesia, Royal City", notes: "Punjab Roadways driver. Retd soon. Savings + pension. Wants simple 3BHK in society near Ferozepur Road bus depot." },
  { name: "Poonam Chhabra", phone: "9872443322", email: "poonam.c@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "Ludhiana — Ferozepur Road", budgetMin: 8000000, budgetMax: 14000000, timeline: "1-3 months", status: "new", source: "99acres", notes: "Joint family. Husband in textile business. 3 kids. Wants spacious 4BHK. Society with playground essential." },
  { name: "Inderpal Singh", phone: "9814332211", email: "inderpal.s@gmail.com", leadType: "buyer", propertyType: "Plot", area: "Ludhiana — Chandigarh Road", budgetMin: 10000000, budgetMax: 20000000, timeline: "Immediately", status: "negotiating", source: "Client Referral", notes: "NRI from Italy. Wants premium plot 300 sq yard on Chandigarh Road. Plans luxury farmhouse-style home." },
  { name: "Geeta Bansal", phone: "9876332211", email: "geeta.bansal@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Ludhiana — Chandigarh Road", budgetMin: 6000000, budgetMax: 11000000, timeline: "3-6 months", status: "interested", source: "Housing.com", projects: "Omaxe Royal Residency, Hero Homes", notes: "Professor at GNE College. Husband at PAU. Want midway home between both workplaces." },
  { name: "Amarjit Kaur", phone: "9815221100", email: "amarjit.k@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Ludhiana — Haibowal", budgetMin: 2000000, budgetMax: 3500000, timeline: "1-3 months", status: "new", source: "Public Form", notes: "Dairy worker. Husband also at dairy. Combined income modest. PMAY eligible. First home. Ground floor." },
  { name: "Surinder Mohan", phone: "9872221100", email: "surinder.m@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Ludhiana — Focal Point", budgetMin: 12000000, budgetMax: 22000000, timeline: "3-6 months", status: "interested", source: "Builder Referral", notes: "Knitwear exporter. Expanding unit. Needs 8000 sq ft shed in Phase 8 or 9. Ceiling height 20ft min." },
  { name: "Bobby Dhaliwal", phone: "9814110099", email: "bobby.dhaliwal@gmail.com", leadType: "buyer", propertyType: "Villa", area: "Ludhiana — Civil Lines", budgetMin: 20000000, budgetMax: 40000000, timeline: "6-12 months", status: "contacted", source: "99acres", notes: "High Court advocate. Wants heritage bungalow in Civil Lines. Old construction okay if plot is large. 500+ sq yard." },
  { name: "Ramandeep Kaur", phone: "9876110099", email: "ramandeep.k@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Ludhiana — Rajguru Nagar", budgetMin: 3000000, budgetMax: 5000000, timeline: "Immediately", status: "new", source: "WhatsApp", notes: "Student counselor at PAU. Single working woman. Wants secure flat near university. First floor preferred." },
  { name: "Harjot Singh", phone: "9815009988", email: "harjot.s@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Ludhiana — Giaspura", budgetMin: 3500000, budgetMax: 6000000, timeline: "3-6 months", status: "contacted", source: "Facebook Ads", notes: "LPU admin staff. Wants affordable 3BHK near university. Okay with slightly older construction if price right." },
  { name: "Nandini Sharma", phone: "9872009988", email: "nandini.sharma@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Ludhiana — Jawaddi", budgetMin: 4500000, budgetMax: 8000000, timeline: "1-3 months", status: "interested", source: "Landing Page", projects: "GBP Athens, Savitry Greens", notes: "Pharmacist at Civil Hospital. Wants gated society near Jawaddi Kalan. Pharmacy nearby for emergency shifts." },
  { name: "Darshan Singh", phone: "9814889977", email: "darshan.s@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Ludhiana — Sherpur", budgetMin: 8000000, budgetMax: 15000000, timeline: "Immediately", status: "site-visit", source: "99acres", notes: "Auto parts manufacturer. Wants industrial plot 4000-6000 sq ft near Sherpur Chowk. GLADA approved. Road access." },
  { name: "Gursimran Kaur", phone: "9876889977", email: "gursimran.k@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Ludhiana — Hambran Road", budgetMin: 3000000, budgetMax: 5500000, timeline: "6-12 months", status: "new", source: "Public Form", notes: "Married couple. Both teachers. Combined salary 60K. Want affordable society near PAU or Hambran Road." },
  { name: "Vikrant Mahajan", phone: "9815778866", email: "vikrant.m@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "Ludhiana — Hambran Road", budgetMin: 7000000, budgetMax: 12000000, timeline: "3-6 months", status: "interested", source: "WhatsApp", projects: "SBP Gateway, GBP Eco Greens", notes: "IT manager. Large family. Wants 4BHK in gated society. Open parking for 2 cars. Kids play area needed." },
];

const patiala = [
  { name: "Avtar Singh Mann", phone: "9814778866", email: "avtar.mann@gmail.com", leadType: "buyer", propertyType: "Villa", area: "Patiala — Model Town", budgetMin: 18000000, budgetMax: 35000000, timeline: "1-3 months", status: "negotiating", source: "Client Referral", notes: "Ex-MLA's relative. Wants premium kothi 400+ sq yard in Model Town Extension. Marble + wooden interiors." },
  { name: "Simran Dhindsa", phone: "9876778866", email: "simran.dhindsa@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Patiala — Model Town", budgetMin: 5000000, budgetMax: 10000000, timeline: "3-6 months", status: "interested", source: "Housing.com", notes: "Lecturer at Thapar University. Husband at Rajindra Hospital. Want society between both workplaces." },
  { name: "Gurbachan Singh", phone: "9815667755", email: "gurbachan.s@gmail.com", leadType: "buyer", propertyType: "5BHK+", area: "Patiala — Sarabha Nagar", budgetMin: 35000000, budgetMax: 65000000, timeline: "6-12 months", status: "interested", source: "Builder Referral", notes: "Land-owning family. Wants showpiece mansion in Sarabha Nagar. 600+ sq yard. Grand entrance with fountain." },
  { name: "Baljit Kaur", phone: "9872667755", email: "baljit.k@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Patiala — Rajpura Road", budgetMin: 3500000, budgetMax: 6500000, timeline: "1-3 months", status: "new", source: "WhatsApp", projects: "Royal City, Omaxe City", notes: "Husband runs dairy farm. Moving to city for children's education. Near good CBSE school essential." },
  { name: "Dr. Manpreet Kaur", phone: "9814556644", email: "manpreet.doc@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Patiala — Rajpura Road", budgetMin: 8000000, budgetMax: 15000000, timeline: "Immediately", status: "site-visit", source: "99acres", notes: "Gynecologist. Wants to open maternity clinic on Rajpura Road. 2000 sq ft. Ground floor. Ambulance access." },
  { name: "Harmeet Singh Bajwa", phone: "9876556644", email: "harmeet.bajwa@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "Patiala — Urban Estate Phase 1", budgetMin: 10000000, budgetMax: 20000000, timeline: "3-6 months", status: "interested", source: "Housing.com", notes: "Commissioner-level govt officer. Wants independent floor 250 sq yard. Security important. Park-facing." },
  { name: "Rani Devi", phone: "9815445533", email: "rani.devi@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Patiala — Urban Estate Phase 2", budgetMin: 2500000, budgetMax: 5000000, timeline: "Immediately", status: "contacted", source: "Public Form", notes: "Anganwadi supervisor. Widow. Government pension. Wants affordable flat. PMAY eligible. Near Gurudwara." },
  { name: "Sanjeev Kumar", phone: "9872445533", email: "sanjeev.k.ptl@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Patiala — Leela Bhawan / Mall Road", budgetMin: 12000000, budgetMax: 25000000, timeline: "1-3 months", status: "negotiating", source: "Builder Referral", notes: "Optician. Wants showroom on Mall Road. 800-1200 sq ft. Glass front mandatory. Near existing eyewear shops." },
  { name: "Jagjit Singh Randhawa", phone: "9814334422", email: "jagjit.randhawa@gmail.com", leadType: "buyer", propertyType: "Plot", area: "Patiala — Leela Bhawan / Mall Road", budgetMin: 25000000, budgetMax: 50000000, timeline: "6-12 months", status: "interested", source: "Client Referral", notes: "NRI from California. Wants commercial plot on Mall Road for mixed-use development. 300+ sq yard." },
  { name: "Parveen Kumar", phone: "9876334422", email: "parveen.k@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Patiala — New Mahindra Colony", budgetMin: 3500000, budgetMax: 6500000, timeline: "1-3 months", status: "new", source: "Facebook Ads", notes: "Railway employee. Posted in Patiala Junction. Wants flat near railway station. Transfer possible in 5 years." },
  { name: "Rupinder Kaur", phone: "9815223311", email: "rupinder.k@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Patiala — Tripuri", budgetMin: 1800000, budgetMax: 3500000, timeline: "3-6 months", status: "contacted", source: "Landing Page", notes: "Safai karamchari. SC quota benefits. Wants EWS flat under govt scheme. PUDA housing board preferred." },
  { name: "Tejinder Singh", phone: "9872223311", email: "tejinder.s@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Patiala — Tripuri", budgetMin: 3000000, budgetMax: 5500000, timeline: "Immediately", status: "new", source: "WhatsApp", notes: "Truck driver. Saved over 15 years. Wants 3BHK for family. Wife and 4 kids. Near Tripuri gurudwara." },
  { name: "Dr. Amarjeet Singh", phone: "9814112200", email: "amarjeet.doc@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "Patiala — Punjabi University Area", budgetMin: 8000000, budgetMax: 15000000, timeline: "3-6 months", status: "site-visit", source: "99acres", notes: "Dean at Punjabi University. Wants spacious home near campus. Garden mandatory. Academic community preferred." },
  { name: "Komal Arora", phone: "9876112200", email: "komal.arora@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Patiala — Punjabi University Area", budgetMin: 1800000, budgetMax: 3200000, timeline: "Immediately", status: "new", source: "Public Form", notes: "PG hostel investor. Wants cheap 2BHK near university to rent to students. ROI 6-8% expected." },
  { name: "Major Singh", phone: "9815001199", email: "major.singh@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Patiala — Focal Point", budgetMin: 12000000, budgetMax: 22000000, timeline: "1-3 months", status: "interested", source: "99acres", notes: "Bicycle seat manufacturer. Expanding from Ludhiana. Needs 6000-8000 sq ft shed. Power 60 KVA. PSIEC allotment." },
  { name: "Nirmal Singh", phone: "9872001199", email: "nirmal.s@gmail.com", leadType: "buyer", propertyType: "Villa", area: "Patiala — Lower Mall / Old Patiala", budgetMin: 10000000, budgetMax: 22000000, timeline: "6-12 months", status: "contacted", source: "WhatsApp", notes: "History professor. Loves Patiala heritage. Wants old haveli to restore. Near Qila Mubarak. Tourism potential." },
  { name: "Harleen Kaur Bhullar", phone: "9814990088", email: "harleen.b@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Patiala — Sangrur Road", budgetMin: 3000000, budgetMax: 6000000, timeline: "3-6 months", status: "new", source: "Facebook Ads", projects: "GBP Rosewood, Gillco Parkhills", notes: "Nurse at Rajindra Hospital. Newlywed. Home loan from Punjab & Sind Bank. Wants modern society with security." },
  { name: "Gurmukh Singh", phone: "9876990088", email: "gurmukh.s@gmail.com", leadType: "buyer", propertyType: "Plot", area: "Patiala — Sangrur Road", budgetMin: 3000000, budgetMax: 7000000, timeline: "1-3 months", status: "interested", source: "99acres", notes: "Retired JCO. Army pension. Wants PUDA plot 150 sq yard. Plans to build 2 floors. Sons in Army will fund." },
  { name: "Kanwaljeet Singh", phone: "9815889977", email: "kanwaljeet.s@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Patiala — Sirhind Road", budgetMin: 3500000, budgetMax: 6500000, timeline: "Immediately", status: "contacted", source: "Landing Page", notes: "Works at Verka Milk Plant. Stable income. Wants society flat near Sirhind Road. School bus route important." },
  { name: "Baldev Raj", phone: "9872889977", email: "baldev.raj@gmail.com", leadType: "buyer", propertyType: "Commercial", area: "Patiala — Bhupindra Road", budgetMin: 10000000, budgetMax: 20000000, timeline: "3-6 months", status: "interested", source: "Housing.com", notes: "Wants shop space for readymade garments. 1000-1500 sq ft. Bhupindra Road for footfall. AC showroom." },
  { name: "Sukhjinder Kaur", phone: "9814778855", email: "sukhjinder.k@gmail.com", leadType: "buyer", propertyType: "2BHK", area: "Patiala — Bahadurgarh Road", budgetMin: 2000000, budgetMax: 4000000, timeline: "6-12 months", status: "new", source: "WhatsApp", notes: "ASHA worker. Modest income. First home dream. PMAY subsidy. Wants small flat near PHC Bahadurgarh Road." },
  { name: "Daljit Singh Bhatti", phone: "9876778855", email: "daljit.bhatti@gmail.com", leadType: "buyer", propertyType: "4BHK", area: "Patiala — Bahadurgarh Road", budgetMin: 6000000, budgetMax: 11000000, timeline: "1-3 months", status: "interested", source: "99acres", notes: "Retd. brigadier. Wants spacious house with garden. Security important. Near cantonment area preferred." },
  { name: "Manjit Kaur Gill", phone: "9815667744", email: "manjit.gill@gmail.com", leadType: "buyer", propertyType: "Villa", area: "Patiala — Civil Lines", budgetMin: 20000000, budgetMax: 40000000, timeline: "3-6 months", status: "site-visit", source: "Client Referral", notes: "NRI family from UK. Want bungalow in Civil Lines. 500 sq yard. Modern construction. Guest house attached." },
  { name: "Harwinder Singh", phone: "9872667744", email: "harwinder.s@gmail.com", leadType: "buyer", propertyType: "3BHK", area: "Patiala — Adalat Bazaar", budgetMin: 4000000, budgetMax: 7000000, timeline: "Immediately", status: "new", source: "Public Form", notes: "Advocate at District Courts. Wants home near court complex. Walking distance to chambers. Ground floor." },
  { name: "Pawandeep Singh", phone: "9814556633", email: "pawandeep.s@gmail.com", leadType: "buyer", propertyType: "Plot", area: "Patiala — Nabha Road", budgetMin: 3000000, budgetMax: 7000000, timeline: "3-6 months", status: "contacted", source: "99acres", notes: "Young farmer selling ancestral land. Wants to invest in city plot. 150-200 sq yard. PUDA approved." },
];

const now = Date.now();
let count = 0;

[...gurgaon, ...ludhiana, ...patiala].forEach(b => {
  const offset = Math.floor(Math.random() * 45 * 24 * 60 * 60 * 1000);
  db.createLead({ ...b, createdAt: now - offset });
  count++;
});

console.log(`Seeded ${count} additional leads (${gurgaon.length} Gurgaon + ${ludhiana.length} Ludhiana + ${patiala.length} Patiala)`);
